=== andrewbheyer/ts_sal/xml/SALCommandSet.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="unqualified"
        attributeFormDefault="unqualified">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
     SAL Command data item schema for LSST
    </xsd:documentation>
  </xsd:annotation>

 <xsd:element name="SALCommandSet">
 <xsd:complexType>
 <xsd:sequence>

 <xsd:element name="SALCommand" minOccurs="1" maxOccurs="unbounded">
  <xsd:complexType>
   <xsd:sequence>
      <xsd:element   name="Subsystem"     type="xsd:string"/>
      <xsd:element   name="Version"       type="xsd:decimal"/>
      <xsd:element   name="Author"        type="xsd:string"/>
      <xsd:element   name="EFDB_Topic"    type="xsd:string"/>
      <xsd:element   name="Alias"         type="xsd:string"/>
      <xsd:element   name="Device"        type="xsd:string"/>
      <xsd:element   name="Property"      type="xsd:string"/>
      <xsd:element   name="Action"        type="xsd:string"/>
      <xsd:element   name="Value"         type="xsd:string"/>
      <xsd:element   name="Explanation"   minOccurs="0" maxOccurs="1"  type="xsd:anyURI"/>
      <xsd:element   name="item" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
        <xsd:sequence>
              <xsd:element name="EFDB_Name"     type="xsd:string"/>
              <xsd:element name="Description"   type="xsd:string"/>
              <xsd:element name="IDL_Type"      type="xsd:string"/>
              <xsd:element name="Units"         type="xsd:string"/>

              <xsd:element name="Count">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:positiveInteger">
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
        </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

   </xsd:sequence>
  </xsd:complexType>
 </xsd:element> 

 </xsd:sequence>
 </xsd:complexType>
 </xsd:element> 

 <xsd:attribute name="updateDate"    type="xsd:date"/>

</xsd:schema>

=== andrewbheyer/ts_sal/lsstsal/scripts/xml/validated/camera_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="SALCommandSet.xsd">

<SALCommand>
 <Subsystem>camera</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_command_configure</EFDB_Topic>
 <Alias>configure</Alias>
 <Device>configure</Device>
 <Property></Property>
 <Action></Action>
 <Value></Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/camera_command_configure.html</Explanation>
    <item>
      <EFDB_Name>specId</EFDB_Name>
      <Description> </Description>
      <IDL_Type>string</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALCommand>

<SALCommand>
 <Subsystem>camera</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_command_filter</EFDB_Topic>
 <Alias>filter</Alias>
 <Device>filter</Device>
 <Property>position</Property>
 <Action></Action>
 <Value></Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/camera_command_filter.html</Explanation>
    <item>
      <EFDB_Name>name</EFDB_Name>
      <Description> </Description>
      <IDL_Type>string</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALCommand>

<SALCommand>
 <Subsystem>camera</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_command_guideStars</EFDB_Topic>
 <Alias>guideStars</Alias>
 <Device>guiders</Device>
 <Property>roi</Property>
 <Action>set</Action>
 <Value></Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/camera_command_guideStars.html</Explanation>
    <item>
      <EFDB_Name>xpos</EFDB_Name>
      <Description> </Description>
      <IDL_Type>double</IDL_Type>
      <Units> </Units>
      <Count>8</Count>
    </item>
    <item>
      <EFDB_Name>ypos</EFDB_Name>
      <Description> </Description>
      <IDL_Type>double</IDL_Type>
      <Units> </Units>
      <Count>8</Count>
    </item>
    <item>
      <EFDB_Name>roiSize</EFDB_Name>
      <Description> </Description>
      <IDL_Type>int</IDL_Type>
      <Units> </Units>
      <Count>8</Count>
    </item>
</SALCommand>

<SALCommand>
 <Subsystem>camera</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_command_image</EFDB_Topic>
 <Alias>image</Alias>
 <Device>imager</Device>
 <Property>expose</Property>
 <Action></Action>
 <Value></Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/camera_command_image.html</Explanation>
    <item>
      <EFDB_Name>numImages</EFDB_Name>
      <Description> </Description>
      <IDL_Type>int</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>expTime</EFDB_Name>
      <Description> </Description>
      <IDL_Type>double</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>shutter</EFDB_Name>
      <Description> </Description>
      <IDL_Type>boolean</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>guide</EFDB_Name>
      <Description> </Description>
      <IDL_Type>booean</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>wfs</EFDB_Name>
      <Description> </Description>
      <IDL_Type>boolean</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALCommand>

<SALCommand>
 <Subsystem>camera</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_command_status</EFDB_Topic>
 <Alias>status</Alias>
 <Device>status</Device>
 <Property></Property>
 <Action></Action>
 <Value></Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/camera_command_status.html</Explanation>
</SALCommand>
</SALCommandSet>

=== andrewbheyer/ts_sal/lsstsal/xml/validated/dome_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="SALCommandSet.xsd">

<SALCommand>
 <Subsystem>dome</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>dome_command_closeShutter</EFDB_Topic>
 <Alias>closeShutter</Alias>
 <Device>shutter</Device>
 <Property>position</Property>
 <Action>close</Action>
 <Value></Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/dome_command_closeShutter.html</Explanation>
</SALCommand>

<SALCommand>
 <Subsystem>dome</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>dome_command_louvers</EFDB_Topic>
 <Alias>louvers</Alias>
 <Device>louvers</Device>
 <Property>position</Property>
 <Action>set</Action>
 <Value></Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/dome_command_louvers.html</Explanation>
    <item>
      <EFDB_Name>angle</EFDB_Name>
      <Description> </Description>
      <IDL_Type>double</IDL_Type>
      <Units> </Units>
      <Count>72</Count>
    </item>
</SALCommand>

<SALCommand>
 <Subsystem>dome</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>dome_command_movetoCal</EFDB_Topic>
 <Alias>movetoCal</Alias>
 <Device>target</Device>
 <Property>position</Property>
 <Action></Action>
 <Value></Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/dome_command_movetoCal.html</Explanation>
</SALCommand>

<SALCommand>
 <Subsystem>dome</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>dome_command_openShutter</EFDB_Topic>
 <Alias>openShutter</Alias>
 <Device>shutter</Device>
 <Property>position</Property>
 <Action>open</Action>
 <Value></Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/dome_command_openShutter.html</Explanation>
</SALCommand>

<SALCommand>
 <Subsystem>dome</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>dome_command_park</EFDB_Topic>
 <Alias>park</Alias>
 <Device>target</Device>
 <Property>position</Property>
 <Action></Action>
 <Value></Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/dome_command_park.html</Explanation>
</SALCommand>

<SALCommand>
 <Subsystem>dome</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>dome_command_target</EFDB_Topic>
 <Alias>target</Alias>
 <Device>target</Device>
 <Property>position</Property>
 <Action></Action>
 <Value></Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/dome_command_target.html</Explanation>
    <item>
      <EFDB_Name>azimuth</EFDB_Name>
      <Description> </Description>
      <IDL_Type>string</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>elevation</EFDB_Name>
      <Description> </Description>
      <IDL_Type>string</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALCommand>

<SALCommand>
 <Subsystem>dome</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>dome_command_test</EFDB_Topic>
 <Alias>test</Alias>
 <Device>test</Device>
 <Property>any</Property>
 <Action>any</Action>
 <Value></Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/dome_command_test.html</Explanation>
</SALCommand>

<SALCommand>
 <Subsystem>dome</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>dome_command_track</EFDB_Topic>
 <Alias>track</Alias>
 <Device>track</Device>
 <Property>mode</Property>
 <Action>string</Action>
 <Value>mode</Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/dome_command_track.html</Explanation>
</SALCommand>
</SALCommandSet>

=== andrewbheyer/ts_sal/xml/validated/tcs_Commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="SALCommandSet.xsl"?>
<SALCommandSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="SALCommandSet.xsd">

<SALCommand>
 <Subsystem>tcs</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>tcs_command_wepCalculate</EFDB_Topic>
 <Alias>wepCalculate</Alias>
 <Device>wep</Device>
 <Property>zernikes</Property>
 <Action>calculate</Action>
 <Value></Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/tcs_command_wepCalculate.html</Explanation>
    <item>
      <EFDB_Name>uid</EFDB_Name>
      <Description> </Description>
      <IDL_Type>string<64></IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALCommand>

<SALCommand>
 <Subsystem>tcs</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>tcs_command_wepSimulate</EFDB_Topic>
 <Alias>wepSimulate</Alias>
 <Device>wep</Device>
 <Property>zernikes</Property>
 <Action>simulate</Action>
 <Value></Value>
 <Explanation>http://sal.lsst.org/SAL/Commands/tcs_command_wepSimulate.html</Explanation>
    <item>
      <EFDB_Name>uid</EFDB_Name>
      <Description> </Description>
      <IDL_Type>string<64></IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>z_arr</EFDB_Name>
      <Description> </Description>
      <IDL_Type>double</IDL_Type>
      <Units> </Units>
      <Count>18</Count>
    </item>
</SALCommand>
</SALCommandSet>
