=== andrewbheyer/ts_sal/xml/SALEventSet.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="unqualified"
        attributeFormDefault="unqualified">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
     SAL Event data item schema for LSST
    </xsd:documentation>
  </xsd:annotation>

 <xsd:element name="SALEventSet">
 <xsd:complexType>
 <xsd:sequence>

  <xsd:element name="SALEvent" minOccurs="1" maxOccurs="unbounded">
   <xsd:complexType>
    <xsd:sequence>
      <xsd:element   name="Subsystem"     type="xsd:string"/>
      <xsd:element   name="Version"       type="xsd:decimal"/>
      <xsd:element   name="Author"        type="xsd:string"/>
      <xsd:element   name="EFDB_Topic"    type="xsd:string"/>
      <xsd:element   name="Alias"         type="xsd:string"/>
      <xsd:element   name="Explanation"   minOccurs="0" maxOccurs="1"  type="xsd:anyURI"/>
      <xsd:element   name="item" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>

              <xsd:element name="EFDB_Name"     type="xsd:string"/>
              <xsd:element name="Description"   type="xsd:string"/>

              <xsd:element name="IDL_Type"        type="xsd:string"/>
              <xsd:element name="Units"           type="xsd:string"/>

              <xsd:element name="Count">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:positiveInteger">
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>

              <xsd:element name="Explanation"      minOccurs="0" maxOccurs="1"  type="xsd:anyURI"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
   
    </xsd:sequence>
   </xsd:complexType>
  </xsd:element>


 </xsd:sequence>
 </xsd:complexType>
 </xsd:element> 

 <xsd:attribute name="updateDate"    type="xsd:date"/>

</xsd:schema>

=== andrewbheyer/ts_sal/lsstsal/scripts/xml-templates/MTMount/MTMount_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://lsst-sal.tuc.noao.edu/schema/SALEventSet.xsd">

<SALEvent>
 <Subsystem>MTMount</Subsystem>
<<<<<<< HEAD
 <Version>2.5.3</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>MTMount_logevent_accLimit</EFDB_Topic>
 <Alias>accLimit</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/MTMount_logevent_accLimit.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>MTMount</Subsystem>
 <Version>2.5.3</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>MTMount_logevent_altLimit</EFDB_Topic>
 <Alias>altLimit</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/MTMount_logevent_altLimit.html</Explanation>
    <item>
      <EFDB_Name>priority</EFDB_Name>
      <Description>Severity of the event</Description>
      <IDL_Type>long</IDL_Type>
      <Units>NA</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>type</EFDB_Name>
      <Description> </Description>
       <IDL_Type>string</IDL_Type>
      <Units> </Units>
=======
 <Version>3.0</Version>
 <Author>Ander Ansuategi</Author>
 <EFDB_Topic>MTMount_logevent_mountState</EFDB_Topic>
 <Alias>mountState</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/MTMount_mountState.html</Explanation>
    <item>
      <EFDB_Name>id</EFDB_Name>
      <Description>Identifier of the state</Description>
      <IDL_Type>long</IDL_Type>
      <Units></Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>text</EFDB_Name>
      <Description>The state of the state machine</Description>
       <IDL_Type>string</IDL_Type>
      <Units></Units>
>>>>>>> release/Release-3-RC1
      <Count>1</Count>
    </item>
</SALEvent>

<SALEvent>
 <Subsystem>MTMount</Subsystem>
<<<<<<< HEAD
 <Version>2.5.3</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>MTMount_logevent_interlock</EFDB_Topic>
 <Alias>interlock</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/MTMount_logevent_interlock.html</Explanation>
    <item>
      <EFDB_Name>priority</EFDB_Name>
      <Description>Severity of the event</Description>
      <IDL_Type>long</IDL_Type>
      <Units>NA</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>detail</EFDB_Name>
      <Description> </Description>
       <IDL_Type>string</IDL_Type>
      <Units> </Units>
=======
 <Version>3.0</Version>
 <Author>Ander Ansuategi</Author>
 <EFDB_Topic>MTMount_logevent_mountWarning</EFDB_Topic>
 <Alias>mountWarning</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/MTMount_mountWarning.html</Explanation>
    <item>
      <EFDB_Name>id</EFDB_Name>
      <Description>Identifier of the warning</Description>
      <IDL_Type>long</IDL_Type>
      <Units></Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>text</EFDB_Name>
      <Description>The warning info</Description>
       <IDL_Type>string</IDL_Type>
      <Units></Units>
>>>>>>> release/Release-3-RC1
      <Count>1</Count>
    </item>
</SALEvent>

<SALEvent>
 <Subsystem>MTMount</Subsystem>
<<<<<<< HEAD
 <Version>2.5.3</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>MTMount_logevent_powerError</EFDB_Topic>
 <Alias>powerError</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/MTMount_logevent_powerError.html</Explanation>
    <item>
      <EFDB_Name>priority</EFDB_Name>
      <Description>Severity of the event</Description>
      <IDL_Type>long</IDL_Type>
      <Units>NA</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>device</EFDB_Name>
      <Description> </Description>
       <IDL_Type>string</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>severity</EFDB_Name>
      <Description> </Description>
       <IDL_Type>long</IDL_Type>
      <Units> </Units>
=======
 <Version>3.0</Version>
 <Author>Ander Ansuategi</Author>
 <EFDB_Topic>MTMount_logevent_mountError</EFDB_Topic>
 <Alias>mountError</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/MTMount_mountError.html</Explanation>
    <item>
      <EFDB_Name>id</EFDB_Name>
      <Description>Identifier of the error</Description>
      <IDL_Type>long</IDL_Type>
      <Units></Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>text</EFDB_Name>
      <Description>The error info</Description>
       <IDL_Type>string</IDL_Type>
      <Units></Units>
>>>>>>> release/Release-3-RC1
      <Count>1</Count>
    </item>
</SALEvent>

<SALEvent>
 <Subsystem>MTMount</Subsystem>
<<<<<<< HEAD
 <Version>2.5.3</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>MTMount_logevent_slewError</EFDB_Topic>
 <Alias>slewError</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/MTMount_logevent_slewError.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>MTMount</Subsystem>
 <Version>2.5.3</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>MTMount_logevent_slewOK</EFDB_Topic>
 <Alias>slewOK</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/MTMount_logevent_slewOK.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>MTMount</Subsystem>
 <Version>2.5.3</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>MTMount_logevent_slewReady</EFDB_Topic>
 <Alias>slewReady</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/MTMount_logevent_slewReady.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>MTMount</Subsystem>
 <Version>2.5.3</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>MTMount_logevent_tempError</EFDB_Topic>
 <Alias>tempError</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/MTMount_logevent_tempError.html</Explanation>
    <item>
      <EFDB_Name>priority</EFDB_Name>
      <Description>Severity of the event</Description>
      <IDL_Type>long</IDL_Type>
      <Units>NA</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>device</EFDB_Name>
      <Description> </Description>
       <IDL_Type>string</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>severity</EFDB_Name>
      <Description> </Description>
       <IDL_Type>long</IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALEvent>

<SALEvent>
 <Subsystem>MTMount</Subsystem>
 <Version>2.5.3</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>MTMount_logevent_trackLost</EFDB_Topic>
 <Alias>trackLost</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/MTMount_logevent_trackLost.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>MTMount</Subsystem>
 <Version>2.5.3</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>MTMount_logevent_tracking</EFDB_Topic>
 <Alias>tracking</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/MTMount_logevent_tracking.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>MTMount</Subsystem>
 <Version>2.5.3</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>MTMount_logevent_velLimit</EFDB_Topic>
 <Alias>velLimit</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/MTMount_logevent_velLimit.html</Explanation>
=======
 <Version>3.0</Version>
 <Author>Ander Ansuategi</Author>
 <EFDB_Topic>MTMount_logevent_mountInPosition</EFDB_Topic>
 <Alias>mountInPosition</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/MTMount_mountInPosition.html</Explanation>
    <item>
      <EFDB_Name>inposition</EFDB_Name>
      <Description>Whether the mount is in position or not</Description>
      <IDL_Type>boolean</IDL_Type>
      <Units></Units>
      <Count>1</Count>
    </item>
>>>>>>> release/Release-3-RC1
</SALEvent>
</SALEventSet>

=== andrewbheyer/ts_sal/xml/validated/camera_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="SALEventSet.xsd">

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_ccsConfigured</EFDB_Topic>
 <Alias>ccsConfigured</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_ccsConfigured.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_endInitializeGuider</EFDB_Topic>
 <Alias>endInitializeGuider</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_endInitializeGuider.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_endInitializeImage</EFDB_Topic>
 <Alias>endInitializeImage</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_endInitializeImage.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_endReadout</EFDB_Topic>
 <Alias>endReadout</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_endReadout.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_endSetFilter</EFDB_Topic>
 <Alias>endSetFilter</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_endSetFilter.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_endShutterClose</EFDB_Topic>
 <Alias>endShutterClose</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_endShutterClose.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_endShutterOpen</EFDB_Topic>
 <Alias>endShutterOpen</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_endShutterOpen.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_endTakeImage</EFDB_Topic>
 <Alias>endTakeImage</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_endTakeImage.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_startIntegration</EFDB_Topic>
 <Alias>startIntegration</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_startIntegration.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_startReadout</EFDB_Topic>
 <Alias>startReadout</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_startReadout.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_startSetFilter</EFDB_Topic>
 <Alias>startSetFilter</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_startSetFilter.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_startShutterClose</EFDB_Topic>
 <Alias>startShutterClose</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_startShutterClose.html</Explanation>
</SALEvent>

<SALEvent>
 <Subsystem>camera</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>camera_logevent_startShutterOpen</EFDB_Topic>
 <Alias>startShutterOpen</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/camera_logevent_startShutterOpen.html</Explanation>
</SALEvent>
</SALEventSet>

=== andrewbheyer/ts_sal/lsstsal/scripts/xml/validated/tcs_Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="SALEventSet.xsl"?>
<SALEventSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="SALEventSet.xsd">

<SALEvent>
 <Subsystem>tcs</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>tcs_logevent_wfsdataReady</EFDB_Topic>
 <Alias>wfsdataReady</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/tcs_logevent_wfsdataReady.html</Explanation>
    <item>
      <EFDB_Name>priority</EFDB_Name>
      <Description>Severity of the event</Description>
      <IDL_Type>long</IDL_Type>
      <Units>NA</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>images_location_URI</EFDB_Name>
      <Description> </Description>
      <IDL_Type>string<256></IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>images_match_URI</EFDB_Name>
      <Description> </Description>
      <IDL_Type>string<64></IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALEvent>

<SALEvent>
 <Subsystem>tcs</Subsystem>
 <Version>2.4</Version>
 <Author>salgenerator</Author>
 <EFDB_Topic>tcs_logevent_zemaxError</EFDB_Topic>
 <Alias>zemaxError</Alias>
 <Explanation>http://sal.lsst.org/SAL/Events/tcs_logevent_zemaxError.html</Explanation>
    <item>
      <EFDB_Name>priority</EFDB_Name>
      <Description>Severity of the event</Description>
      <IDL_Type>long</IDL_Type>
      <Units>NA</Units>
      <Count>1</Count>
    </item>
    <item>
      <EFDB_Name>details</EFDB_Name>
      <Description> </Description>
      <IDL_Type>string<128></IDL_Type>
      <Units> </Units>
      <Count>1</Count>
    </item>
</SALEvent>
</SALEventSet>
